services:
  postgres-db:
    container_name: postgres-db
    image: postgres:16-alpine
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    expose:
      - "5432:5432"
    restart: always

  django-backend:
    container_name: django-backend
    build:
      context: .
      dockerfile: ./dockerfiles/dev/django/Dockerfile
    env_file:
      - .env
    volumes:
      - ./core:/usr/src/app
    working_dir: /usr/src/app
    command: python manage.py runserver 0.0.0.0:8001
    ports:
      - "8001:8001"
    restart: always
    depends_on:
      - postgres-db

  smtp4dev:
    image: rnwood/smtp4dev:v3
    restart: always
    ports:
      - '5000:80'
      - '25:25'
      - '143:143'
    volumes:
      - smtp4dev-data:/smtp4dev
    environment:
      - ServerOptions__HostName=smtp4dev

volumes:
  smtp4dev-data:
